class_name GetIconResource

# Icon type
enum IconType {
	Keystone = 0,
	Mapstone = 1,
	BreakableWall = 2,
	BreakableWallBroken = 3,
	StompableFloor = 4,
	StompableFloorBroken = 5,
	EnergyGateTwo = 6,
	EnergyGateOpen = 7,
	KeystoneDoorFour = 8,
	KeystoneDoorOpen = 9,
	AbilityPedestal = 10,
	HealthUpgrade = 11,
	EnergyUpgrade = 12,
	SavePedestal = 13,
	AbilityPoint = 14,
	KeystoneDoorTwo = 15,
	Experience = 17,
	MapstonePickup = 18,
	EnergyGateTwelve = 19,
	EnergyGateTen = 20,
	EnergyGateEight = 21,
	EnergyGateSix = 22,
	EnergyGateFour = 23,
	SpiritShard = 24,
	NPC = 25,
	QuestItem = 26,
	ShardSlotUpgrade = 27,
	Teleporter = 28,
	Ore = 29,
	QuestStart = 30,
	QuestEnd = 31,
	RaceStart = 32,
	HealthFragment = 33,
	EnergyFragment = 34,
	Seed = 35,
	RaceEnd = 36,
	Eyestone = 37,
	WatermillDoor = 40,
	TempleDoor = 41,
	SmallDoor = 42,
	Shrine = 43,
	ShrineFinished = 44,
	Loremaster = 50,
	Weaponmaster = 51,
	Gardener = 52,
	Mapmaker = 53,
	Shardtrader = 54,
	Wanderer = 55,
	Treekeeper = 56,
	Builder = 57,
	Kwolok = 58,
	Statistician = 59,
	CreepHeart = 60,
	Miner = 61,
	Spiderling = 62,
	Moki = 63,
	MokiBrave = 64,
	MokiAdventurer = 65,
	MokiArtist = 66,
	MokiDarkness = 67,
	MokiFashionable = 68,
	MokiFisherman = 69,
	MokiFrozen = 70,
	MokiKwolokAmulet = 71,
	MokiSpyglass = 72,
	Ku = 73,
	IceFisher = 74,
	Siira = 75,
	SavePedestalInactive = 76,
	RaceStartFinished = 77,
	RaceEndFinished = 78,
	CleanWater = 100,
	BonusItem = 101,
	LaunchFragment = 102,
	PurpleFloor = 103,
	PurpleWall = 104,
	YellowWall = 105,
	OneWayWallLeft = 106,
	OneWayWallRight = 107,
	IceWall = 108,
	IceFloor = 109,
	VerticalDoor = 110,
	HorizontalDoor = 111,
	Lever = 112,
	Door = 113,
	DoorUnknown = 114,
	DoorSmall = 115,
	DoorSmallUnknown = 116,
	Wisp = 117,
}

static var Icon_Resource_Dict : Dictionary = {
	IconType.Keystone: "pickups/resource/Keystone.png",
	IconType.Eyestone: "pickups/resource/Eyestone.png",
	IconType.EnergyFragment: "pickups/resource/Energy.png",
	IconType.HealthFragment: "pickups/resource/Health.png",
	IconType.Experience: "pickups/resource/SpiritLight.png",
	IconType.Ore: "pickups/resource/Ore.png",
	IconType.SpiritShard: "pickups/Shard.png",
	IconType.Seed: "pickups/Seed.png",
	IconType.Wisp: "pickups/Wisp.png",
	IconType.ShardSlotUpgrade: "pickups/resource/ShardSlot.png",
	IconType.Teleporter: "Teleporter.png",
	IconType.AbilityPedestal: "pickups/SkillTree.png",
	IconType.KeystoneDoorTwo: "DoorKeystone2.png",
	IconType.KeystoneDoorFour: "DoorKeystone4.png",
	IconType.RaceStart: "trials/RaceStart.png",
	IconType.RaceEnd: "trials/RaceFinish.png",
	IconType.Shrine: "trials/Shrine.png",
	IconType.CreepHeart: "WillowHeart.png",
	IconType.QuestItem: "pickups/QuestReward.png",
	IconType.Moki: "npc/Moki.png",
	IconType.MokiBrave: "npc/Moki.png",
	IconType.MokiAdventurer: "npc/Moki.png",
	IconType.MokiArtist: "npc/Moki.png",
	IconType.MokiDarkness: "npc/Moki.png",
	IconType.MokiFashionable: "npc/Moki.png",
	IconType.MokiFisherman: "npc/Moki.png",
	IconType.MokiFrozen: "npc/Moki.png",
	IconType.MokiKwolokAmulet: "npc/Moki.png",
	IconType.MokiSpyglass: "npc/Moki.png",
	IconType.Mapmaker: "npc/Lupo.png",
	IconType.Gardener: "npc/Veral.png",
	IconType.Builder: "npc/Grom.png",
	IconType.Treekeeper: "npc/Kii.png",
	IconType.Weaponmaster: "npc/Opher.png",
	IconType.Shardtrader: "npc/Twillen.png"
}


static func get_icon_resource(icon_id: int) -> String:
	return "res://assets/icons/%s" % Icon_Resource_Dict.get(icon_id, "Unknown.png")
